/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AddUserFrame.java
 *
 * Created on 2010-1-15, 10:25:11
 */

package email;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.DateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author root
 */
public class AddUserFrame extends javax.swing.JFrame {

    /** Creates new form AddUserFrame */
    public AddUserFrame(MailFuncInter mailinter) {
        m_mailInter=mailinter;
        initComponents();
        initCombo();                                                            //combobox
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextUsermessage = new javax.swing.JTextField();
        jTextPower = new javax.swing.JTextField();
        jTextAccounts = new javax.swing.JTextField();
        jComboMailtype = new javax.swing.JComboBox();
        jComboPostfix = new javax.swing.JComboBox();
        jButtonadd = new javax.swing.JButton();
        jButtonreset = new javax.swing.JButton();
        jButtonexit = new javax.swing.JButton();
        jTextPassword = new javax.swing.JTextField();
        jComboRevAuto = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(email.EmailApp.class).getContext().getResourceMap(AddUserFrame.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N

        jLabel5.setText(resourceMap.getString("jLabel5.text")); // NOI18N
        jLabel5.setName("jLabel5"); // NOI18N

        jLabel6.setText(resourceMap.getString("jLabel6.text")); // NOI18N
        jLabel6.setName("jLabel6"); // NOI18N

        jTextUsermessage.setText(resourceMap.getString("jTextUsermessage.text")); // NOI18N
        jTextUsermessage.setName("jTextUsermessage"); // NOI18N

        jTextPower.setText(resourceMap.getString("jTextPower.text")); // NOI18N
        jTextPower.setName("jTextPower"); // NOI18N

        jTextAccounts.setText(resourceMap.getString("jTextAccounts.text")); // NOI18N
        jTextAccounts.setName("jTextAccounts"); // NOI18N

        jComboMailtype.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "163", "126", "yeah", "qq", "sina" }));
        jComboMailtype.setName("jComboMailtype"); // NOI18N
        jComboMailtype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboMailtypeActionPerformed(evt);
            }
        });

        jComboPostfix.setName("jComboPostfix"); // NOI18N
        jComboPostfix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboPostfixActionPerformed(evt);
            }
        });

        jButtonadd.setText(resourceMap.getString("jButtonadd.text")); // NOI18N
        jButtonadd.setName("jButtonadd"); // NOI18N
        jButtonadd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonaddMouseClicked(evt);
            }
        });

        jButtonreset.setText(resourceMap.getString("jButtonreset.text")); // NOI18N
        jButtonreset.setName("jButtonreset"); // NOI18N
        jButtonreset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonresetMouseClicked(evt);
            }
        });

        jButtonexit.setText(resourceMap.getString("jButtonexit.text")); // NOI18N
        jButtonexit.setName("jButtonexit"); // NOI18N
        jButtonexit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonexitMouseClicked(evt);
            }
        });

        jTextPassword.setText(resourceMap.getString("jTextPassword.text")); // NOI18N
        jTextPassword.setName("jTextPassword"); // NOI18N

        jComboRevAuto.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "是", "否" }));
        jComboRevAuto.setName("jComboRevAuto"); // NOI18N

        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(jLabel1))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jTextAccounts, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextUsermessage, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel3))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(4, 4, 4)
                                        .addComponent(jTextPower, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButtonreset, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jComboRevAuto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jComboMailtype, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(19, 19, 19)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jComboPostfix, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonexit, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonadd, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                        .addGap(263, 263, 263))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextUsermessage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jTextPower, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextAccounts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jTextPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jComboMailtype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboPostfix, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboRevAuto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonadd)
                    .addComponent(jButtonreset)
                    .addComponent(jButtonexit))
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonresetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonresetMouseClicked
        // TODO add your handling code here:
        this.jTextUsermessage.setText(null);
        this.jTextPower.setText(null);
        this.jTextAccounts.setText(null);
        this.jTextPassword.setText(null);
    }//GEN-LAST:event_jButtonresetMouseClicked

    private void jButtonexitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonexitMouseClicked
        // TODO add your handling code here:
        //m_mailInter.Disconnectdb();
        this.dispose();
    }//GEN-LAST:event_jButtonexitMouseClicked

    private void jButtonaddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonaddMouseClicked
        try 
        {
            // TODO add your handling code here:
           // m_mailInter.Connectdb();                                            //connect database

            if (CheckDate())                                                    //check the date is empty or not
            {
                int count=0;
                String accounts=jTextAccounts.getText();
                String postfix=(String) jComboPostfix.getSelectedItem();
                String user=accounts+"@"+postfix;
                String selsql="select count(*) from emailaccounts where accounts='"+user+"'";
                count=m_mailInter.Excutesql(selsql);
                if(count!=0)
                {
                    JOptionPane.showMessageDialog(null, "该用户已经存在！");
                    return;
                }
                String password=jTextPassword.getText();
                String userMessage=jTextUsermessage.getText();
                String power=jTextPower.getText();
                String logo="vip";
                String MailType=(String) jComboMailtype.getSelectedItem();
                Date now = new Date(System.currentTimeMillis());
		DateFormat date = DateFormat.getDateInstance();

		String addtime = date.format(now);
                int revAuto=jComboRevAuto.getSelectedIndex();
                int auto=0;
                if(revAuto==0)
                {
                    auto=1;
                }
                int state=0;
                String sql = "insert into emailaccounts(ID,accounts,password,PostFix,userMessage,logo,Power,MailType,AddTime,AutoRev,RevState)" +
                        " values (null,'"+accounts+"','"+password+"','"+postfix+"','"+userMessage+"','"+logo+"','"+power+"','"+MailType+"','"+addtime+"','"+auto+"','"+state+"')";
                count=m_mailInter.Excutemdl(sql);
                if(count==1)
                {
                    JOptionPane.showMessageDialog(null, "添加成功！");
                    m_mailInter.RefashTable();
                }
                
            }
            else
            {
                return;
            }
        } 
        catch (Exception ex) {
            Logger.getLogger(AddUserFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
       
    }//GEN-LAST:event_jButtonaddMouseClicked

    private void jComboMailtypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboMailtypeActionPerformed
        // TODO add your handling code here:
        jComboPostfix.removeAllItems();
        int  selectIndex=jComboMailtype.getSelectedIndex();
        switch(selectIndex)
        {
 /*          case 0:
                jComboPostfix.addItem("hotmail.com");
                jComboPostfix.addItem("live.com");
                jComboPostfix.addItem("live.cn");
                jComboPostfix.addItem("msn.cn");
                jComboPostfix.addItem("msn.com");
                jComboPostfix.addItem("hotmail.de");
                jComboPostfix.addItem("hotmail.co.jp");
                jComboPostfix.addItem("hotmail.co.uk");
                jComboPostfix.addItem("livemail.tw");
                jComboPostfix.addItem("livemail.it");
                break;
            case 1:
                jComboPostfix.addItem("yahoo.com");
                jComboPostfix.addItem("yahoo.com.cn");
                jComboPostfix.addItem("yahoo.cn");
                jComboPostfix.addItem("yahoo.co.jp");
                jComboPostfix.addItem("yahoo.com.tw");
                jComboPostfix.addItem("yahoo.de");
                jComboPostfix.addItem("yahoo.co.uk");
                jComboPostfix.addItem("yahoo.fr");
                jComboPostfix.addItem("yahoo.co.in");
                jComboPostfix.addItem("yahoo.co.kr");
                jComboPostfix.addItem("yahoo.co.hk");
                jComboPostfix.addItem("ymail.com");
                jComboPostfix.addItem("btinternet.com");
                jComboPostfix.addItem("rocketmail.com");
                break;*/
            case 0:
                 jComboPostfix.addItem("163.com");
                 break;
        /*    case 3:
                 jComboPostfix.addItem("fastmail.fm");
                 break;
            case 4:
                 jComboPostfix.addItem("mail.ru");
                 jComboPostfix.addItem("inbox.ru");
                 break;*/
            case 1:
                 jComboPostfix.addItem("126.com");
                 break;
            case 2:
                 jComboPostfix.addItem("yeah.net");
                 break;
            case 3:
                 jComboPostfix.addItem("qq.com");
                 break;
            case 4:
                 jComboPostfix.addItem("sina.com");
                 jComboPostfix.addItem("sina.cn");
                 break;
 /*           case 6:
                 jComboPostfix.addItem("ms63.hinet.net");
                 jComboPostfix.addItem("msa.hinet.net");
                 break;
            case 7:
                 jComboPostfix.addItem("gmail.com");
                 break;*/
            default:
                break;
        }

    }//GEN-LAST:event_jComboMailtypeActionPerformed

    private void jComboPostfixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboPostfixActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboPostfixActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MailFuncInter mail = null;
                new AddUserFrame(mail ).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonadd;
    private javax.swing.JButton jButtonexit;
    private javax.swing.JButton jButtonreset;
    private javax.swing.JComboBox jComboMailtype;
    private javax.swing.JComboBox jComboPostfix;
    private javax.swing.JComboBox jComboRevAuto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTextAccounts;
    private javax.swing.JTextField jTextPassword;
    private javax.swing.JTextField jTextPower;
    private javax.swing.JTextField jTextUsermessage;
    // End of variables declaration//GEN-END:variables

    private MailFuncInter m_mailInter;
    public Statement stmt;
    public ResultSet result;
    public Connection con;

    /**
     * check date empty or not
     * @return
     */
    private boolean CheckDate() {

        String check=null;
        check=jTextUsermessage.getText();
        if(check.length()==0)
        {
            JOptionPane.showMessageDialog( null, "备注信息不能为空！","提示",JOptionPane.ERROR_MESSAGE);
            return false;
        }
        if(jTextPower.getText().length()==0)
        {
            JOptionPane.showMessageDialog( null, "用户属主不能为空！","提示",JOptionPane.ERROR_MESSAGE);
            return false;
        }
        if(jTextAccounts.getText().length()==0)
        {
            JOptionPane.showMessageDialog( null, "用户名不能为空！","提示",JOptionPane.ERROR_MESSAGE);
             return false;
        }
        if(jTextPassword.getText().length()==0)
        {
            JOptionPane.showMessageDialog( null, "密码不能为空！","提示",JOptionPane.ERROR_MESSAGE);
             return false;
        }
        return true;
    }

    private void initCombo() {

        jComboMailtype.setEditable(false);
        jComboPostfix.setEditable(false);
        jTextUsermessage.requestFocus();
        jComboMailtype.setSelectedIndex(-1);
    }

}
