/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ConfigureFrame.java
 *
 * Created on 2010-1-23, 9:36:30
 */

package email;


import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;


/**
 *
 * @author root
 */
public class ConfigureFrame extends javax.swing.JFrame {

    /** Creates new form ConfigureFrame */
    public ConfigureFrame(MailFuncInter mailinter) {

        initComponents();
        m_mailInter=mailinter;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonYes = new javax.swing.JButton();
        jButtonNo = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldPath = new javax.swing.JTextField();
        jButtonChoose = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBoxThreadNumber = new javax.swing.JComboBox();
        jComboBoxTimespace = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jTextUrl = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(email.EmailApp.class).getContext().getResourceMap(ConfigureFrame.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N

        jButtonYes.setText(resourceMap.getString("jButtonYes.text")); // NOI18N
        jButtonYes.setName("jButtonYes"); // NOI18N
        jButtonYes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonYesMouseClicked(evt);
            }
        });

        jButtonNo.setText(resourceMap.getString("jButtonNo.text")); // NOI18N
        jButtonNo.setName("jButtonNo"); // NOI18N
        jButtonNo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonNoMouseClicked(evt);
            }
        });

        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        jTextFieldPath.setText(resourceMap.getString("jTextFieldPath.text")); // NOI18N
        jTextFieldPath.setName("jTextFieldPath"); // NOI18N

        jButtonChoose.setText(resourceMap.getString("jButtonChoose.text")); // NOI18N
        jButtonChoose.setName("jButtonChoose"); // NOI18N
        jButtonChoose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonChooseMouseClicked(evt);
            }
        });

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        jComboBoxThreadNumber.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "10", "20", "30", "40", "50", "100", "200", "500", "1000" }));
        jComboBoxThreadNumber.setName("jComboBoxThreadNumber"); // NOI18N

        jComboBoxTimespace.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "5", "10", "30", "50", "100", "200", "500", "10000" }));
        jComboBoxTimespace.setName("jComboBoxTimespace"); // NOI18N

        jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N

        jTextUrl.setText(resourceMap.getString("jTextURL.text")); // NOI18N
        jTextUrl.setName("jTextURL"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButtonYes)
                        .addGap(71, 71, 71)
                        .addComponent(jButtonNo)
                        .addGap(112, 112, 112))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(30, 30, 30)
                                .addComponent(jComboBoxThreadNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                                .addComponent(jLabel2)
                                .addGap(34, 34, 34)
                                .addComponent(jComboBoxTimespace, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(47, 47, 47))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(33, 33, 33)
                                .addComponent(jTextFieldPath, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonChoose, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextUrl, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldPath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonChoose)
                            .addComponent(jLabel1)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTextUrl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(114, 114, 114)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jComboBoxThreadNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jComboBoxTimespace, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonNo)
                    .addComponent(jButtonYes))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonChooseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonChooseMouseClicked
        // TODO add your handling code here:
        JFileChooser MailFolder = new JFileChooser(".");
        MailFolder.setDialogTitle("路径选择");
        MailFolder.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);

        int iState = MailFolder.showDialog(MailFolder, "确定");
        if(iState==0)
        {
            File file=MailFolder.getSelectedFile();
            this.jTextFieldPath.setText(file.toString());
        }
    }//GEN-LAST:event_jButtonChooseMouseClicked

    private void jButtonNoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonNoMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButtonNoMouseClicked

    private void jButtonYesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonYesMouseClicked
        // TODO add your handling code here:
        try {

            if(CheckData())
            {
                String path = "/";
                String mailPath = this.jTextFieldPath.getText().trim();                                           //邮件保存路径
                String urlpath=this.jTextUrl.getText().trim();//cookie 后台URL地址
             //   String password=this.jTextPass.getText().trim();
                if(mailPath.length()==0)
                {
                    File file=new File(".");
                    mailPath=file.toString();
                }
             //   if(password.length()==0)
              //  {
               //     password=null;
              //  }
                String timespace = (String) this.jComboBoxTimespace.getSelectedItem();                                          //时间间隔
                String ThreadNumber=(String) this.jComboBoxThreadNumber.getSelectedItem();                          //线程数
                String config="Mail Path: "+mailPath+";\n"+"Time Space: "+timespace+";\n"+"Max ThreadNumber: "+ThreadNumber+";\n"+"CookieUrl: "+urlpath+";\n";
                File directory = new File(".");
                File file = new File(directory.getCanonicalPath() + path);
                if (file.exists()) {
                    //System.out.println("文件夹存在");
                } else {
                    // System.out.println("文件夹不存在，正在创建...");
                    if (file.mkdirs()) {
                        //System.out.println("文件创建成功！");
                    } else {
                        // System.out.println("文件创建失败！");
                    }
                }
                String fileName = "user.conf";
                File newfile = new File(directory.getCanonicalPath() + path + fileName);
                if (!newfile.exists())
                {
                    newfile.createNewFile();
                    BufferedWriter output = new BufferedWriter(new FileWriter(newfile, true));
                    output.write(config);
                    //output.close();
                    output.flush();
                    JOptionPane.showMessageDialog(null, "配置文件生成成功!","提示",JOptionPane.INFORMATION_MESSAGE);
                }
                else
                {
                    BufferedWriter output = new BufferedWriter(new FileWriter(newfile, false));
                    output.write(config);
                    //output.close();
                    output.flush();
                    JOptionPane.showMessageDialog(null, "配置文件生成成功!","提示",JOptionPane.INFORMATION_MESSAGE);
                    //JOptionPane.showMessageDialog(null, "配置文件已经存在！","提示",JOptionPane.INFORMATION_MESSAGE);
                }
            }
            else
            {
                JOptionPane.showMessageDialog(null, "请完善信息!","提示",JOptionPane.INFORMATION_MESSAGE);
                return;
            }
        } catch (IOException ex)
        {
            Logger.getLogger(DatabaseSettingFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonYesMouseClicked

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MailFuncInter mail=null;
                new ConfigureFrame(mail).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonChoose;
    private javax.swing.JButton jButtonNo;
    private javax.swing.JButton jButtonYes;
    private javax.swing.JComboBox jComboBoxThreadNumber;
    private javax.swing.JComboBox jComboBoxTimespace;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextFieldPath;
    private javax.swing.JTextField jTextUrl;
    // End of variables declaration//GEN-END:variables
    private MailFuncInter m_mailInter;

    private boolean CheckData() {

        return true;
    }
}
